Repository irshadmd/Awesome-CSS-Projects, pull requests merged in 2022-10, with the labels that each got.

#6 Calculator
  calculator.html
Labels: Hacktoberfest, hacktoberfest-accepted

#10 Calculator
  Calculator/calculator.html
Labels: Hacktoberfest, hacktoberfest-accepted

#8 cat pic with/without bkg
  Cat scan/img/arrow.png
  Cat scan/img/cat full.jpg
  Cat scan/img/cat trans.png
  Cat scan/img/trans bkg.jpg
  Cat scan/index.html
  Cat scan/index.js
  Cat scan/style.css
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#28 Add .gitignore
  .DS_Store
  .gitignore
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#26 Digital Clock with dark mode
  Digital Clock/Demo/demo.gif
  Digital Clock/index.html
  Digital Clock/script.js
  Digital Clock/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#44 feat: Added City Skyline project
  CitySkyline/demo/demo.gif
  CitySkyline/index.html
  CitySkyline/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#29 Added HoverBoard Project
  HoverBoard/demo/demo.gif
  HoverBoard/index.html
  HoverBoard/script.js
  HoverBoard/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#57 Added Parallax Card Sample Resolves #30
  Parallax Card/Demo/Demo.gif
  Parallax Card/index.html
  Parallax Card/script.js
  Parallax Card/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#59 Fixed URL for game.html
  pixi game/index.html
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#62 Added cool cookie monster project
  Cookiemonster/README.md
  Cookiemonster/audio/nom2.mp4
  Cookiemonster/audio/snack_time!.mp4
  Cookiemonster/css/style.css
  Cookiemonster/demo/demo.gif
  Cookiemonster/index.html
  Cookiemonster/js/master.js
Labels: Hacktoberfest, hacktoberfest-accepted

#55 Issue25: Added Moving Car Animation
  MovingCarAnimation/Demo/demo.gif
  MovingCarAnimation/Pictures/Img_02.png
  MovingCarAnimation/Pictures/bg.png
  MovingCarAnimation/Pictures/car.png
  MovingCarAnimation/index.html
  MovingCarAnimation/script.js
  MovingCarAnimation/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#70 Added Bubbles Effect
  Bubbles Effect/demo/Demo.gif
  Bubbles Effect/index.html
  Bubbles Effect/ocean.jpg
  Bubbles Effect/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#69 Added Dice Game
  Dice Game/Demo/Demo.gif
  Dice Game/images/dice1.png
  Dice Game/images/dice2.png
  Dice Game/images/dice3.png
  Dice Game/images/dice4.png
  Dice Game/images/dice5.png
  Dice Game/images/dice6.png
  Dice Game/index.html
  Dice Game/index.js
  Dice Game/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#77 Made a quote generator
  Quote Generator/Demo/demo.gif
  Quote Generator/index.html
  Quote Generator/script.js
  Quote Generator/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#49 Make iPhone 6 - CSS only
  iPhone-6/Demo/demo.gif
  iPhone-6/index.html
  iPhone-6/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#66 Added snakes and ladders
  Snakes and Ladders/demo/demo.gif
  Snakes and Ladders/game.css
  Snakes and Ladders/game.html
  Snakes and Ladders/games.jpeg
Labels: Hacktoberfest, hacktoberfest-accepted

#46 add neon btn
  neon-btn/demo/demo.gif
  neon-btn/index.html
  neon-btn/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#47 Added Rock Paper Scissors
  Rock Paper Scissors/README.md
  Rock Paper Scissors/demo.gif
  Rock Paper Scissors/game.css
  Rock Paper Scissors/game.js
  Rock Paper Scissors/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#81 Added Water Wave Text Effect
  Water Wavy Text/Demo/Demo.gif
  Water Wavy Text/index.html
  Water Wavy Text/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#93 Speech to text
  Speech-to-text/README.md
  Speech-to-text/demo/demo.gif
  Speech-to-text/index.html
  Speech-to-text/script.js
  Speech-to-text/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#103 Add Cat Facts Generator
  Cat Facts Generator/demo/demo.gif
  Cat Facts Generator/index.html
  Cat Facts Generator/script.js
  Cat Facts Generator/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#85 Snake Animation using Keyframes
  SnakeAnimation/demo/demo.gif
  SnakeAnimation/index.html
  SnakeAnimation/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#99 Added quiz app based on CSS
  Quiz App/demo/demo.gif
  Quiz App/index.html
  Quiz App/js/questions.js
  Quiz App/js/script.js
  Quiz App/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#119 Added Before-After Image Slider
  Before-After Image Slider/demo/demo.gif
  Before-After Image Slider/images/after.jpg
  Before-After Image Slider/images/before.jpg
  Before-After Image Slider/index.html
  Before-After Image Slider/main.js
  Before-After Image Slider/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#124 addfavicon to dice game
  Dice Game/images/favicon.ico
  Dice Game/index.html
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#131 Animated Disc in background
  Disc/demo/demo.gif
  Disc/index.html
  Disc/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#132 Flying Dots Animation
  FlyingDots/demo/demo.gif
  FlyingDots/index.html
  FlyingDots/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#145 BUG resolved by adding files
  Linktree Alternative/bg.png
  Linktree Alternative/index.html
  Linktree Alternative/myimg.png
  Linktree Alternative/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#17 Pokemons
  Pokemons/.vscode/settings.json
  Pokemons/demo/demo.gif
  Pokemons/images/Pokemons.png
  Pokemons/index.html
  Pokemons/pokemon.css
  Pokemons/pokemon.js
  Pokemons/pokemon.json
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#128 Age Calculator
  Age Calculator/Age.html
  Age Calculator/Age.js
  Age Calculator/Style.css
  Age Calculator/demo/demo.gif
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#129 added profile-card to projects
  Animated profile card/demo/demo.gif
  Animated profile card/index.html
  Animated profile card/style.css
  Animated profile card/vanilla-tilt.js
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#135 Add Discord Landing Page
  Discord Landing Page/AQCT.ttf
  Discord Landing Page/bootstrap.css
  Discord Landing Page/demo/demo.gif
  Discord Landing Page/images/bg.svg
  Discord Landing Page/images/card1.svg
  Discord Landing Page/images/card2.svg
  Discord Landing Page/images/card3.svg
  Discord Landing Page/images/conclude.svg
  Discord Landing Page/images/sparkle.svg
  Discord Landing Page/index.html
  Discord Landing Page/script.js
  Discord Landing Page/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#138 Added Image Slider
  ImageSlider/demo/demo.gif
  ImageSlider/index.html
  ImageSlider/slider.png
  ImageSlider/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#163 Contribute to awesome css projects - viviane martini
  Thas-all-folks-animation/demo/demo.gif
  Thas-all-folks-animation/index.html
  Thas-all-folks-animation/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#164 added playDrum project (fixed files that were missing)
  playDrum/Demo/demo.gif
  playDrum/images/crash.png
  playDrum/images/kick.png
  playDrum/images/snare.png
  playDrum/images/tom1.png
  playDrum/images/tom2.png
  playDrum/images/tom3.png
  playDrum/images/tom4.png
  playDrum/index.html
  playDrum/index.js
  playDrum/sounds/crash.mp3
  playDrum/sounds/kick-bass.mp3
  playDrum/sounds/snare.mp3
  playDrum/sounds/tom-1.mp3
  playDrum/sounds/tom-2.mp3
  playDrum/sounds/tom-3.mp3
  playDrum/sounds/tom-4.mp3
  playDrum/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#168 Added Insect Catch Game using HTML ,CSS JS
  Insect-Catch-Game/demo/demo.gif
  Insect-Catch-Game/index.html
  Insect-Catch-Game/script.js
  Insect-Catch-Game/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#169 Employee Cards
  Employee Card/Demo/demo.gif
  Employee Card/Employee_Card.html
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#172 Create Sorting Visualizer
  Sorting Visulaizer/demo/demo.gif
  Sorting Visulaizer/index.html
  Sorting Visulaizer/script.js
  Sorting Visulaizer/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#177 Added Color Game
  Color Game/css/style.css
  Color Game/demo/demo.gif
  Color Game/index.html
  Color Game/js/script.js
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#178 Tetris Game
  Tetris/Src/background.mp3
  Tetris/Src/gameOver.mp3
  Tetris/Src/point.mp3
  Tetris/Src/tetris.png
  Tetris/demo/demo.gif
  Tetris/index.html
  Tetris/script.js
  Tetris/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#180 temperature convertor added
  temperature convertor/README.md
  temperature convertor/demo/demo.gif
  temperature convertor/index.html
  temperature convertor/js/script.js
  temperature convertor/styles/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#183 Added Password Generator
  Password_Generator/demo/demo.gif
  Password_Generator/index.html
  Password_Generator/script.js
  Password_Generator/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#193 Added QR Generator
  QR Generator/demo/demo.gif
  QR Generator/index.css
  QR Generator/index.html
  QR Generator/index.js
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#203 Added Floating Input Fields
  Floating-Input-field/demo/demo.gif
  Floating-Input-field/index.html
  Floating-Input-field/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#205 Weather App Added
  Weather App/Weather.jpg
  Weather App/demo/demo.gif
  Weather App/index.html
  Weather App/script.js
  Weather App/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#213 The Simon Game
  The Simon Game/.vscode/settings.json
  The Simon Game/Demo.gif/Demo-GameOver.gif
  The Simon Game/Demo.gif/Demo-Gameplay.gif
  The Simon Game/game.js
  The Simon Game/index.html
  The Simon Game/sounds/blue.mp3
  The Simon Game/sounds/green.mp3
  The Simon Game/sounds/red.mp3
  The Simon Game/sounds/wrong.mp3
  The Simon Game/sounds/yellow.mp3
  The Simon Game/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge

#221 Added Math4Kids Game
  Math4Kids/audio/wrong.mp3
  Math4Kids/demo/demo.gif
  Math4Kids/divide.html
  Math4Kids/index.html
  Math4Kids/multiply.html
  Math4Kids/scripts/add.js
  Math4Kids/scripts/divide.js
  Math4Kids/scripts/multiply.js
  Math4Kids/scripts/subtract.js
  Math4Kids/styles/style.css
  Math4Kids/subtract.html
Labels: Hacktoberfest, hacktoberfest-accepted, ready-to-merge
